// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Travel.Modules.Flights.Infrastructure.Persistence;

#nullable disable

namespace Travel.Modules.Flights.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlightsDbContext))]
    partial class FlightsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flights")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Travel.Modules.Flights.Infrastructure.Persistence.Entities.DeeplinkOfferCacheEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CriteriaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("criteria_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("OffersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("offers_json");

                    b.HasKey("Id")
                        .HasName("pk_deeplink_offers_cache");

                    b.HasIndex("CriteriaHash", "ExpiresAt")
                        .HasDatabaseName("ix_deeplink_offers_cache_criteria_hash_expires_at");

                    b.ToTable("deeplink_offers_cache", "flights");
                });

            modelBuilder.Entity("Travel.Modules.Flights.Infrastructure.Persistence.Entities.IdempotencyKeyEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<string>("ResponseHash")
                        .HasColumnType("text")
                        .HasColumnName("response_hash");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Key")
                        .HasName("pk_idempotency_keys");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_keys_expires_at");

                    b.ToTable("idempotency_keys", "flights");
                });

            modelBuilder.Entity("Travel.Modules.Flights.Infrastructure.Persistence.Entities.OrderReadModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<DateTimeOffset>("BookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("ItineraryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("itinerary_json");

                    b.Property<string>("PassengerInfoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("passenger_info_json");

                    b.Property<string>("ProviderOrderId")
                        .HasColumnType("text")
                        .HasColumnName("provider_order_id");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("TicketNumbers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ticket_numbers");

                    b.Property<DateTimeOffset?>("TicketedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ticketed_at");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_order_read_model");

                    b.HasIndex("AggregateId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_read_model_aggregate_id");

                    b.HasIndex("UserId", "BookedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_order_read_model_user_id_booked_at");

                    b.ToTable("order_read_model", "flights");
                });

            modelBuilder.Entity("Travel.Modules.Flights.Infrastructure.Persistence.Entities.WebhookInboxEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_webhook_inbox");

                    b.HasIndex("Source", "EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_webhook_inbox_source_event_id");

                    b.ToTable("webhook_inbox", "flights");
                });
#pragma warning restore 612, 618
        }
    }
}
