// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Travel.AI.Persistence;

#nullable disable

namespace Travel.AI.Persistence.Migrations
{
    [DbContext(typeof(AiDbContext))]
    [Migration("20260813200652_CostLedgerMessageIdempotency")]
    partial class CostLedgerMessageIdempotency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ai")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Travel.AI.Persistence.Entities.CostLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_usd");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("MessageIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_identity");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_cost_ledger");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_cost_ledger_correlation_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_cost_ledger_occurred_at");

                    b.HasIndex("MessageIdentity", "CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("ix_cost_ledger_message_identity_correlation_id");

                    b.ToTable("cost_ledger", "ai");
                });
#pragma warning restore 612, 618
        }
    }
}
