<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="SSH.NET" />
        <PackageReference Include="xunit.v3.extensibility.core" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>
</Project>
