<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Travel.Shared.Abstractions\Travel.Shared.Abstractions.csproj" />
    <ProjectReference Include="..\Travel.Shared.Domain\Travel.Shared.Domain.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
