<Project Sdk="Aspire.AppHost.Sdk/13.2.4">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>travel-apphost</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.Nats" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
  </ItemGroup>
</Project>
