using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Options;
using Shouldly;
using Travel.Modules.Flights.Infrastructure.Providers.Duffel;
using Xunit;

namespace Travel.Modules.Flights.Tests.Unit.Providers.Duffel;

/// <summary>
/// Verifier tests are anchored on a fixture computed by the Duffel reference algorithm
/// (Python <c>hmac.new(secret, "{t}.{body}".encode(), sha256).hexdigest()</c>), as
/// documented in <see href="https://duffel.com/docs/guides/receiving-webhooks"/>. The
/// expected hex was generated by an independent script — see commit message — so that
/// passing the "valid signature" case proves the verifier reproduces the Duffel-side
/// computation, not just that it agrees with itself.
/// </summary>
public sealed class DuffelWebhookVerifierTests
{
    private const string Secret = "whsec_test_duffel_v1_fixture";
    private const string Timestamp = "1700000000";

    // Body matches the Python fixture used to compute ExpectedHex.
    private static readonly byte[] Body = Encoding.UTF8.GetBytes(
        """{"id":"evt_fixture","type":"order.created"}"""
    );

    // Independently computed by:
    //   python3 -c "import hmac,hashlib;
    //               print(hmac.new(b'whsec_test_duffel_v1_fixture',
    //                              b'1700000000.{...body...}',
    //                              hashlib.sha256).hexdigest())"
    private const string ExpectedHex =
        "bdaf4355e36c030386083b2d84b1b9cc40543cb5f5dc452fe5df1e40a58f2188";

    private const string ValidHeader = $"t={Timestamp},v1={ExpectedHex}";

    private static DuffelWebhookVerifier CreateVerifier(string secret = Secret)
    {
        var opts = Options.Create(new DuffelOptions { WebhookSecret = secret });
        return new DuffelWebhookVerifier(opts);
    }

    [Fact]
    public void Verify_valid_signature_returns_true()
    {
        var verifier = CreateVerifier();

        var result = verifier.Verify(Body, ValidHeader);

        result.ShouldBeTrue();
    }

    [Fact]
    public void Verify_field_order_reversed_returns_true()
    {
        // The Duffel docs show "t=...,v1=..." but the spec is a comma-separated list of
        // key=value pairs, so a forward-compatible parser must not require a particular order.
        var verifier = CreateVerifier();

        var result = verifier.Verify(Body, $"v1={ExpectedHex},t={Timestamp}");

        result.ShouldBeTrue();
    }

    [Fact]
    public void Verify_tampered_body_returns_false()
    {
        var verifier = CreateVerifier();
        var tampered = Encoding.UTF8.GetBytes("""{"id":"evt_fixture","type":"order.cancelled"}""");

        var result = verifier.Verify(tampered, ValidHeader);

        result.ShouldBeFalse();
    }

    [Fact]
    public void Verify_tampered_timestamp_returns_false()
    {
        // Re-package the same v1 digest under a different timestamp — must fail because
        // the signed payload is "timestamp.body", so changing the timestamp invalidates it.
        var verifier = CreateVerifier();

        var result = verifier.Verify(Body, $"t=1700000001,v1={ExpectedHex}");

        result.ShouldBeFalse();
    }

    [Fact]
    public void Verify_tampered_v1_returns_false()
    {
        var verifier = CreateVerifier();
        // Flip the last hex char.
        var corrupted = ExpectedHex[..^1] + (ExpectedHex[^1] == '8' ? '9' : '8');

        var result = verifier.Verify(Body, $"t={Timestamp},v1={corrupted}");

        result.ShouldBeFalse();
    }

    [Fact]
    public void Verify_wrong_secret_returns_false()
    {
        var verifier = CreateVerifier(secret: "whsec_some_other_secret");

        var result = verifier.Verify(Body, ValidHeader);

        result.ShouldBeFalse();
    }

    [Fact]
    public void Verify_null_header_returns_false()
    {
        var verifier = CreateVerifier();

        verifier.Verify(Body, null).ShouldBeFalse();
    }

    [Fact]
    public void Verify_empty_header_returns_false()
    {
        var verifier = CreateVerifier();

        verifier.Verify(Body, "").ShouldBeFalse();
    }

    [Fact]
    public void Verify_missing_t_field_returns_false()
    {
        var verifier = CreateVerifier();

        verifier.Verify(Body, $"v1={ExpectedHex}").ShouldBeFalse();
    }

    [Fact]
    public void Verify_missing_v1_field_returns_false()
    {
        var verifier = CreateVerifier();

        verifier.Verify(Body, $"t={Timestamp}").ShouldBeFalse();
    }

    [Fact]
    public void Verify_malformed_header_no_equals_returns_false()
    {
        var verifier = CreateVerifier();

        verifier.Verify(Body, "this-is-not-a-valid-header").ShouldBeFalse();
    }

    [Fact]
    public void Verify_legacy_sha256_prefix_header_returns_false()
    {
        // The verifier previously accepted "sha256=<hex>". That format is NOT what Duffel
        // sends; ensure such a header is rejected after the migration to the v1 scheme.
        var verifier = CreateVerifier();
        var legacyKey = Encoding.UTF8.GetBytes(Secret);
        var legacyHex = Convert
            .ToHexString(HMACSHA256.HashData(legacyKey, Body))
            .ToLowerInvariant();

        verifier.Verify(Body, $"sha256={legacyHex}").ShouldBeFalse();
    }

    [Fact]
    public void Verify_non_hex_v1_returns_false()
    {
        var verifier = CreateVerifier();

        verifier.Verify(Body, $"t={Timestamp},v1=not-valid-hex!!!").ShouldBeFalse();
    }

    [Fact]
    public void Verify_empty_secret_returns_false()
    {
        var verifier = CreateVerifier(secret: "");

        verifier.Verify(Body, ValidHeader).ShouldBeFalse();
    }

    [Fact]
    public void Verify_duplicate_t_field_returns_false()
    {
        var verifier = CreateVerifier();

        verifier.Verify(Body, $"t={Timestamp},t=1700000001,v1={ExpectedHex}").ShouldBeFalse();
    }
}
